// AUTO-GENERATED by `cargo test -p bettor-desktop`. Do not edit.
// Source of truth: src-tauri/src/commands.rs

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Reports the math engine's version.
 */
async engineInfo() : Promise<EngineInfo> {
    return await TAURI_INVOKE("engine_info");
},
/**
 * Converts a price in any format to decimal odds.
 */
async toDecimal(value: string, format: OddsFormat) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("to_decimal", { value, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expresses a decimal price in every other format.
 */
async fromDecimal(decimal: number) : Promise<Result<OddsView, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("from_decimal", { decimal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Converts a probability to the American price implying it.
 */
async impliedToAmerican(prob: number) : Promise<number> {
    return await TAURI_INVOKE("implied_to_american", { prob });
},
/**
 * Converts a probability to the decimal price implying it.
 * 
 * The frontend needs this to show fair odds beside a devigged or modelled
 * probability. It cannot compute `1 / p` itself — that is math, and math
 * lives in the core.
 */
async impliedToDecimal(prob: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("implied_to_decimal", { prob }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Computes the hold on a two-sided market.
 */
async calculateHold(impliedA: number, impliedB: number) : Promise<Result<Hold, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_hold", { impliedA, impliedB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ranks books on the same market by hold, cheapest first.
 * 
 * Rows that fail validation are kept with their error rather than dropped, so
 * a book never silently vanishes from the table.
 */
async compareVig(books: BookInput[]) : Promise<BookRow[]> {
    return await TAURI_INVOKE("compare_vig", { books });
},
/**
 * Runs every devig method against a market.
 */
async devigAll(impliedProbs: number[]) : Promise<DevigRow[]> {
    return await TAURI_INVOKE("devig_all", { impliedProbs });
},
/**
 * Total implied probability of a market, before any devig.
 */
async marketOverround(impliedProbs: number[]) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("market_overround", { impliedProbs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Completes a partially-entered set of probabilities with the leftover one.
 */
async completeSimplex(partial: number[]) : Promise<Result<number[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_simplex", { partial }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expected value of a bet against a fair probability.
 */
async evVsFair(fairProb: number, betImplied: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ev_vs_fair", { fairProb, betImplied }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expected value of a bet at a price and true probability.
 */
async expectedValue(decimal: number, trueProb: number, stake: number) : Promise<Result<ExpectedValue, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("expected_value", { decimal, trueProb, stake }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kelly stake for a price, probability, and bankroll.
 */
async kelly(decimal: number, trueProb: number, bankroll: number, multiplier: number) : Promise<Result<Kelly, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kelly", { decimal, trueProb, bankroll, multiplier }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Splits a bankroll across every outcome of an arbitrage.
 */
async arbitrage(decimals: number[], totalStake: number) : Promise<Result<Arbitrage, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("arbitrage", { decimals, totalStake }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sizes a hedge against an open position.
 */
async hedge(originalStake: number, originalDecimal: number, hedgeDecimal: number, goal: HedgeGoal) : Promise<Result<Hedge, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hedge", { originalStake, originalDecimal, hedgeDecimal, goal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a parlay from its legs.
 */
async parlay(legs: number[], stake: number) : Promise<Result<Parlay, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parlay", { legs, stake }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Closing line value, measured every way that is defensible.
 */
async clv(betDecimal: number, closeDecimal: number, opposingCloseDecimal: number | null) : Promise<Result<Clv, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clv", { betDecimal, closeDecimal, opposingCloseDecimal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the vig from a two-sided market.
 */
async fairCoverProb(american: number, opposingAmerican: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fair_cover_prob", { american, opposingAmerican }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the market's true line out of a posted line and a fair probability.
 */
async impliedTrueLine(lineValue: number, fairCoverProb: number, stdDev: number, betType: BetType) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("implied_true_line", { lineValue, fairCoverProb, stdDev, betType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices every alternate line around a main line.
 */
async generateLadder(mainLine: number, fairCoverProb: number, stdDev: number, betType: BetType, range: number, step: number) : Promise<Result<Ladder, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_ladder", { mainLine, fairCoverProb, stdDev, betType, range, step }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compares two line-and-price quotes on the same market.
 */
async compareLines(lineA: number, fairProbA: number, lineB: number, fairProbB: number, stdDev: number, betType: BetType) : Promise<Result<LineComparison, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_lines", { lineA, fairProbA, lineB, fairProbB, stdDev, betType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Splits a total around a spread into each side's projected score.
 */
async impliedScores(spread: number, total: number) : Promise<Result<ImpliedScores, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("implied_scores", { spread, total }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every sport preset the frontend populates its pickers from.
 * 
 * Returned from the core rather than re-declared in TypeScript: a
 * mistranscribed σ or regression constant is invisible in a unit test and
 * wrong in every number the calculator prints.
 */
async sportConfig() : Promise<SportConfig> {
    return await TAURI_INVOKE("sport_config");
},
/**
 * Prices every market implied by a scoreline model.
 */
async deriveMarkets(model: MatchModel, maxScore: number, spreadLines: number[], totalLines: number[], allowDraw: boolean) : Promise<Result<MatchMarkets, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("derive_markets", { model, maxScore, spreadLines, totalLines, allowDraw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Regresses a rate toward a baseline and attaches a 90% interval.
 */
async regress(observed: number, baseline: number, sampleSize: number, regressionConstant: number) : Promise<Result<Regressed, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("regress", { observed, baseline, sampleSize, regressionConstant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Traces how a regressed estimate converges as the sample grows.
 */
async convergenceSeries(observed: number, baseline: number, regressionConstant: number, maxSample: number, steps: number) : Promise<Result<ConvergencePoint[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convergence_series", { observed, baseline, regressionConstant, maxSample, steps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a middle or trap.
 */
async calculateMiddle(market: Market, highSide: MiddleLeg, lowSide: MiddleLeg, stdDev: number) : Promise<Result<Middle, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_middle", { market, highSide, lowSide, stdDev }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a teaser against the book's offered number.
 */
async analyzeTeaser(legs: TeaserLeg[], teaserPoints: number, teaserDecimalOdds: number, stdDev: number) : Promise<Result<Teaser, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_teaser", { legs, teaserPoints, teaserDecimalOdds, stdDev }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a parlay whose legs move together.
 */
async correlatedParlay(probs: number[], correlation: number, seed: string | null, sims: number | null) : Promise<Result<Correlated, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correlated_parlay", { probs, correlation, seed, sims }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Folds a model probability into a market probability.
 */
async betaUpdate(marketProb: number, modelProb: number, marketN: number, modelN: number) : Promise<Result<BetaPosterior, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("beta_update", { marketProb, modelProb, marketN, modelN }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Folds a model into a market across three or more outcomes.
 */
async dirichletUpdate(marketProbs: number[], modelProbs: number[], marketN: number, modelN: number) : Promise<Result<DirichletPosterior, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dirichlet_update", { marketProbs, modelProbs, marketN, modelN }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Combines a market margin and a model margin by precision.
 */
async marginUpdate(marketMargin: number, modelMargin: number, marketStd: number, modelStd: number) : Promise<Result<MarginPosterior, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("margin_update", { marketMargin, modelMargin, marketStd, modelStd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a posterior probability against an available quote.
 */
async edgeVsPrice(posteriorProb: number, decimalOdds: number, threshold: number) : Promise<Result<Edge, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edge_vs_price", { posteriorProb, decimalOdds, threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Simulates a player prop and prices both sides of the line.
 * 
 * Long-running, so it is `async`: Tauri runs `async` commands off the main
 * thread and the window keeps painting.
 */
async simulateProp(n: number, distribution: Distribution, mu: number, varMultiplier: number, lineValue: number, seed: string | null) : Promise<Result<PropSimulation, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulate_prop", { n, distribution, mu, varMultiplier, lineValue, seed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Simulates bankroll survival under flat betting.
 * 
 * Long-running, so it is `async` for the same reason as [`simulate_prop`].
 */
async simulateRuin(input: RuinInput, seed: string | null) : Promise<Result<RuinResult, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulate_ruin", { input, seed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Builds a range of American prices evenly spaced in cents.
 */
async priceLadder(fromAmerican: number, toAmerican: number, stepCents: number) : Promise<Result<number[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("price_ladder", { fromAmerican, toAmerican, stepCents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cents between two American prices, correct across the ±100 pivot.
 */
async centsBetween(fromAmerican: number, toAmerican: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cents_between", { fromAmerican, toAmerican }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Breakeven and required win rate across a range of prices.
 */
async breakevenLadder(americanPrices: number[], targetEdge: number) : Promise<Result<LadderRung[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("breakeven_ladder", { americanPrices, targetEdge }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Translates a fixed cents move into probability points across a price range.
 */
async clvLadder(americanPrices: number[], cents: number) : Promise<Result<ClvRung[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clv_ladder", { americanPrices, cents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a mix of bets for return and for variance.
 */
async betMix(legs: MixLeg[]) : Promise<Result<BetMix, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bet_mix", { legs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Simulates a season of a bet mix many times over.
 * 
 * Long-running, so it is `async` for the same reason as [`simulate_ruin`].
 */
async simulateSeason(input: SeasonInput, seed: string | null) : Promise<Result<SeasonResult, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulate_season", { input, seed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a bet.
 */
async addBet(draft: BetDraft) : Promise<Result<Bet, LogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_bet", { draft }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replaces a recorded bet — settling it, or correcting a typo.
 */
async updateBet(id: number, draft: BetDraft) : Promise<Result<Bet, LogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_bet", { id, draft }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a recorded bet.
 */
async deleteBet(id: number) : Promise<Result<null, LogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bet", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists recorded bets, newest first.
 */
async listBets(filter: BetFilter) : Promise<Result<Bet[], LogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_bets", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every sport that appears in the log.
 */
async betLogSports() : Promise<Result<string[], LogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bet_log_sports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a slice of the log and analyses it.
 * 
 * One command rather than two so the rows and the summary can never describe
 * different sets of bets — which is what a separate `list` and `summarise`
 * would produce the moment a filter changed between the calls.
 */
async analyzeBetLog(filter: BetFilter) : Promise<Result<BetLogView, BetLogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_bet_log", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reshapes the log into the bet mix the variance module takes.
 */
async betLogMix(filter: BetFilter, bucketCents: number) : Promise<Result<LedgerMix, BetLogError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bet_log_mix", { filter, bucketCents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Why the bet log is not saving to disk, or `None` when it is.
 * 
 * Surfaced so the UI can say that nothing is being kept, rather than looking
 * like it works until the window closes.
 */
async betLogStatus() : Promise<string | null> {
    return await TAURI_INVOKE("bet_log_status");
},
/**
 * Models a game and grades a spread and a total against it.
 * 
 * One command rather than four so every figure on screen comes from the same
 * distribution. Rebuilding the model per query would let a half-typed input
 * leave the curve describing one game and the grades another.
 */
async analyzeGame(shape: GameShape, spread: number, total: number, curveFrom: number, curveTo: number, curveStep: number) : Promise<Result<GameView, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_game", { shape, spread, total, curveFrom, curveTo, curveStep }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expected value across a range of assumed true probabilities.
 */
async evCurve(decimal: number, fromProb: number, toProb: number, step: number) : Promise<Result<EvPoint[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ev_curve", { decimal, fromProb, toProb, step }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Standard normal CDF, exposed for charting the model directly.
 */
async normalCdf(z: number) : Promise<number> {
    return await TAURI_INVOKE("normal_cdf", { z });
},
/**
 * Converts a win probability to the point spread implying it.
 */
async probToSpread(p: number, stdDev: number) : Promise<number> {
    return await TAURI_INVOKE("prob_to_spread", { p, stdDev });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * An arbitrage opportunity, or the absence of one.
 */
export type Arbitrage = { 
/**
 * Per-outcome stakes, in the order supplied.
 */
legs: ArbitrageLeg[]; 
/**
 * Implied probabilities summed. Below 1.0 means free money.
 */
totalImplied: number; 
/**
 * Profit locked in whichever outcome lands. Negative when not an arb.
 */
profit: number; 
/**
 * [`Self::profit`] as a fraction of total stake.
 */
roi: number }
/**
 * Stake and payout for one leg of an arbitrage.
 */
export type ArbitrageLeg = { 
/**
 * Decimal price for this outcome.
 */
decimal: number; 
/**
 * Probability it implies, 0–1.
 */
implied: number; 
/**
 * Stake to place on it.
 */
stake: number; 
/**
 * Return if it wins, stake included.
 */
payout: number }
/**
 * A bet as it is stored and returned.
 */
export type Bet = { 
/**
 * Row id, assigned on insert.
 */
id: number; 
/**
 * ISO 8601 date the bet was placed.
 */
placedAt: string; 
/**
 * Sport or league, free text.
 */
sport: string; 
/**
 * Market type, free text: moneyline, spread, total, prop.
 */
market: string; 
/**
 * What was actually backed.
 */
selection: string; 
/**
 * Which book.
 */
book: string; 
/**
 * American price taken.
 */
priceTaken: number; 
/**
 * American price this side closed at, when known.
 */
closingPrice: number | null; 
/**
 * American closing price on the other side, when known.
 */
opposingClosingPrice: number | null; 
/**
 * Money risked.
 */
stake: number; 
/**
 * How it finished.
 */
outcome: BetOutcome; 
/**
 * Anything else worth remembering.
 */
notes: string }
/**
 * What one bet was worth, in every sense that can be measured.
 */
export type BetAnalysis = { 
/**
 * Decimal price taken.
 */
decimalTaken: number; 
/**
 * Probability the price taken implies, 0–1. Contains vig.
 */
impliedTaken: number; 
/**
 * Realised profit. `None` while the bet is pending.
 */
profit: number | null; 
/**
 * Probability points gained against the raw closing price.
 * 
 * Available whenever a closing price was recorded, because it compares
 * two vigged numbers and the margins largely cancel.
 */
clvPoints: number | null; 
/**
 * The same move in American cents, measured on the cents axis.
 */
clvCents: number | null; 
/**
 * Fair closing probability, 0–1. `None` without the opposing close.
 */
fairProb: number | null; 
/**
 * Edge against the fair close, as a fraction of stake.
 */
ev: number | null; 
/**
 * The same edge in currency.
 */
evDollars: number | null }
/**
 * The fields a caller supplies when writing a bet.
 * 
 * Separate from [`Bet`] because the id is the database's to assign, and a
 * shape that carries one on the way in invites a caller to invent it.
 */
export type BetDraft = { 
/**
 * ISO 8601 date the bet was placed.
 */
placedAt: string; 
/**
 * Sport or league.
 */
sport: string; 
/**
 * Market type.
 */
market: string; 
/**
 * What was backed.
 */
selection: string; 
/**
 * Which book.
 */
book: string; 
/**
 * American price taken.
 */
priceTaken: number; 
/**
 * American price this side closed at.
 */
closingPrice: number | null; 
/**
 * American closing price on the other side.
 */
opposingClosingPrice: number | null; 
/**
 * Money risked.
 */
stake: number; 
/**
 * How it finished.
 */
outcome: BetOutcome; 
/**
 * Free-text notes.
 */
notes: string }
/**
 * Which bets to return.
 */
export type BetFilter = { 
/**
 * Only bets with this outcome.
 */
outcome: BetOutcome | null; 
/**
 * Only this sport, matched exactly.
 */
sport: string | null; 
/**
 * Only bets placed on or after this ISO date.
 */
fromDate: string | null; 
/**
 * Only bets placed on or before this ISO date.
 */
toDate: string | null }
/**
 * Something that can go wrong reading or analysing the bet log.
 * 
 * Two sources, kept apart. `MathError` must never learn that a disk exists —
 * `bettor-core` has no io — and a caller wants to know whether the log could
 * not be *read* or whether one of the bets in it does not make sense. The
 * frontend matches on `source` and then on the inner `kind`.
 */
export type BetLogError = 
/**
 * The log itself could not be read or written.
 */
{ source: "storage"; error: LogError } | 
/**
 * A bet in the log could not be analysed.
 */
{ source: "math"; error: MathError }
/**
 * A slice of the bet log, with each bet analysed and the whole thing summed.
 */
export type BetLogView = { 
/**
 * The bets themselves, newest first.
 */
bets: Bet[]; 
/**
 * Their analysis, in the same order, plus the summary.
 */
ledger: Ledger }
/**
 * A whole bet mix, priced for both return and ride.
 */
export type BetMix = { 
/**
 * Per-kind breakdown, in the order supplied.
 */
legs: MixLegResult[]; 
/**
 * How many bets the mix contains.
 */
bets: number; 
/**
 * Total money risked.
 */
totalStake: number; 
/**
 * Expected profit over the whole mix.
 */
ev: number; 
/**
 * Expected profit as a fraction of money risked.
 */
roi: number; 
/**
 * The single win rate that would break the mix even, 0–1.
 * 
 * Stake-weighted: `Σ stake / Σ (stake × decimal)`. It answers "what would
 * I need to hit if every bet here hit at the same rate", which is a
 * summary, not a prediction — the bets do not hit at the same rate.
 */
blendedBreakeven: number; 
/**
 * Stake-weighted average of the legs' actual win rates, 0–1.
 */
blendedWinRate: number; 
/**
 * Standard deviation of the mix's total profit, in currency.
 */
sd: number; 
/**
 * [`Self::sd`] as a fraction of money risked.
 */
sdPerUnit: number; 
/**
 * Expected profit divided by its standard deviation.
 * 
 * How much of the swing the edge actually is, over one run of this mix.
 * Below about 0.5 the season is mostly noise no matter how good the bets.
 */
tStat: number; 
/**
 * Bets before the edge clears two standard errors, at this mix's shape.
 */
betsToDetect: number | null }
/**
 * How a bet finished.
 * 
 * Exported as `BetOutcome`: TypeScript has one flat namespace and
 * [`crate::middle::Outcome`] is already in it. Same reason `middle::Leg` and
 * `arbitrage::Leg` are disambiguated on export — the Rust names stay
 * idiomatic, and the collision is resolved once, here.
 */
export type BetOutcome = 
/**
 * Not settled yet. Counted in the book, excluded from every return figure.
 */
"pending" | 
/**
 * Won.
 */
"won" | 
/**
 * Lost.
 */
"lost" | 
/**
 * Pushed — stake returned.
 */
"push" | 
/**
 * Voided or cancelled — stake returned.
 */
"void"
/**
 * Which kind of line is being modelled.
 */
export type BetType = 
/**
 * A point spread.
 */
"spread" | 
/**
 * A total, with a side.
 */
{ total: TotalSide }
/**
 * A Beta posterior over a two-way market.
 */
export type BetaPosterior = { 
/**
 * Prior successes, from the market.
 */
priorAlpha: number; 
/**
 * Prior failures, from the market.
 */
priorBeta: number; 
/**
 * Posterior successes, after folding in the model.
 */
posteriorAlpha: number; 
/**
 * Posterior failures.
 */
posteriorBeta: number; 
/**
 * Posterior probability of the first side, 0–1.
 */
posteriorProb: number; 
/**
 * How far the posterior moved off the market, in probability points.
 * 
 * This is the number to sanity-check: a model that drags a liquid market
 * several points is more likely miscalibrated than right.
 */
shiftFromMarket: number }
/**
 * One book's quote in a vig comparison.
 */
export type BookInput = { 
/**
 * Book name, carried through to the result.
 */
name: string; 
/**
 * Implied probability of side A.
 */
impliedA: number; 
/**
 * Implied probability of side B.
 */
impliedB: number }
/**
 * One row of a vig comparison.
 * 
 * Exactly one of `hold` and `error` is set. Failed rows are kept rather than
 * dropped so a book never silently vanishes from the table.
 */
export type BookRow = { 
/**
 * Book name.
 */
name: string; 
/**
 * The hold it charges, when the quote could be read.
 */
hold: Hold | null; 
/**
 * Why the quote could not be read, when it could not.
 */
error: MathError | null }
/**
 * Closing line value, measured every way that is defensible.
 */
export type Clv = { 
/**
 * Decimal price taken.
 */
betDecimal: number; 
/**
 * Decimal price at the close.
 */
closeDecimal: number; 
/**
 * Probability implied by the price taken, 0–1.
 */
betImplied: number; 
/**
 * Probability implied by the closing price, 0–1. Still contains vig.
 */
closeImplied: number; 
/**
 * `bet/close - 1`. What the TS called CLV, EV, and "cents" alike.
 * 
 * Retained for continuity with the web app, but it is a ratio of prices
 * and should never be compared across different price levels.
 */
ratio: number; 
/**
 * Probability points gained: `close_implied - bet_implied`.
 * 
 * The measure that survives comparison across price levels. Positive
 * means the market moved toward your side after you bet.
 */
probPoints: number; 
/**
 * American cents the line moved, which is what people actually quote.
 * 
 * Reported alongside [`Self::prob_points`] precisely so the gap between
 * the two is visible: fifty cents on a longshot is worth less than twenty
 * on a favorite.
 * 
 * Measured on the cents axis (see [`crate::odds::cents_between`]) rather
 * than by subtracting the two American numbers, which is only the same
 * thing while both prices sit on the same side of even money.
 */
cents: number; 
/**
 * EV against the raw closing price — vig included, so overstated.
 * 
 * This is the number the web app reported as "Expected Value".
 */
evVsRawClose: number; 
/**
 * EV against the devigged closing price.
 * 
 * `None` when the opposing closing price was not supplied, because
 * without it the vig cannot be removed and any figure would be a guess.
 */
evVsFair: number | null; 
/**
 * Fair probability at the close once the vig is removed, 0–1.
 */
fairProb: number | null }
/**
 * What a fixed cents move is worth at one price.
 */
export type ClvRung = { 
/**
 * Price taken.
 */
american: number; 
/**
 * Price taken, decimal.
 */
decimal: number; 
/**
 * Probability it implies, 0–1.
 */
implied: number; 
/**
 * Price after the move.
 */
closedAmerican: number; 
/**
 * Price after the move, decimal.
 */
closedDecimal: number; 
/**
 * Probability the closing price implies, 0–1.
 */
closedImplied: number; 
/**
 * Probability points gained. The currency that compounds a bankroll.
 */
probPoints: number; 
/**
 * `taken / closed - 1` — the ratio measure, retained to be argued with.
 */
ratio: number; 
/**
 * How many times larger the ratio measure looks than the honest one.
 * 
 * Climbs steeply with price. This ratio *is* the misconception.
 */
distortion: number }
/**
 * One point on a convergence curve.
 */
export type ConvergencePoint = { 
/**
 * Sample size at this point.
 */
sampleSize: number; 
/**
 * Regressed estimate at that sample size.
 */
regressed: number }
/**
 * How a correlated parlay prices against its independent counterpart.
 */
export type Correlated = { 
/**
 * Product of the leg probabilities — what a parlay calculator assumes.
 */
independentProb: number; 
/**
 * Joint probability once the legs are coupled.
 */
correlatedProb: number; 
/**
 * Independent price, in decimal odds.
 */
independentDecimal: number; 
/**
 * Correlated price, in decimal odds.
 */
correlatedDecimal: number; 
/**
 * Relative change in probability, as a fraction.
 * 
 * Positive means the correlation helps: the parlay is likelier than the
 * product of its legs.
 */
relativeChange: number; 
/**
 * The correlation actually used, after any clamping.
 */
correlationUsed: number; 
/**
 * True when the requested correlation was outside the range an
 * equicorrelated matrix can represent for this many legs.
 */
correlationWasClamped: boolean; 
/**
 * `None` when solved exactly; `Some(seed)` when simulated.
 * 
 * Crosses the wire as a decimal string — see [`crate::seed_repr`].
 */
simulationSeed: string | null }
/**
 * One rung of a spread-to-probability curve.
 */
export type CurvePoint = { 
/**
 * The line.
 */
spread: number; 
/**
 * Probability the home side covers it, 0–1.
 */
homeCovers: number; 
/**
 * Probability of a push at this line, 0–1.
 */
push: number }
/**
 * Which assumption to make about where the margin sits.
 */
export type DevigMethod = 
/**
 * Equal margin — subtract the overround evenly across outcomes.
 */
"EM" | 
/**
 * Margin proportional to odds — divide through by the book total.
 */
"MPTO" | 
/**
 * Shin (1993) — insider-trading model, marks longshots up more.
 */
"SHIN" | 
/**
 * Odds ratio — find the exponent `c` where `Σ pᶜ = 1`.
 */
"OR" | 
/**
 * Logarithmic — shift every outcome by a constant in log-odds space.
 */
"LOG"
/**
 * One devig method's verdict on a market.
 */
export type DevigRow = { 
/**
 * Which method produced this.
 */
method: DevigMethod; 
/**
 * Human-readable name for display.
 */
name: string; 
/**
 * Fair probabilities, when the method converged.
 */
fairProbs: number[] | null; 
/**
 * Why the method could not produce them, when it could not.
 * 
 * Kept beside the row so the UI can explain an empty column instead of
 * just showing a dash.
 */
error: MathError | null }
/**
 * A Dirichlet posterior over a market with any number of outcomes.
 */
export type DirichletPosterior = { 
/**
 * Prior concentration per outcome, from the market.
 */
priorAlphas: number[]; 
/**
 * Posterior concentration per outcome.
 */
posteriorAlphas: number[]; 
/**
 * Posterior probabilities, summing to 1.
 */
posteriorProbs: number[]; 
/**
 * Largest move off the market across outcomes, in probability points.
 */
maxShiftFromMarket: number }
/**
 * Which family to sample from.
 */
export type Distribution = 
/**
 * Counts with variance equal to the mean. Goals, aces.
 */
"poisson" | 
/**
 * Overdispersed counts — variance a multiple of the mean.
 */
"nbinom" | 
/**
 * Continuous, right-skewed, variance twice the mean.
 */
"gamma" | 
/**
 * Continuous, heavier right tail. Yardage, minutes.
 */
"lognormal"
/**
 * What a posterior is worth against a price on offer.
 */
export type Edge = { 
/**
 * Posterior probability minus the price's implied probability, in points.
 */
edgePoints: number; 
/**
 * Expected value as a fraction of stake.
 */
evFraction: number; 
/**
 * The American price the posterior implies.
 */
fairOdds: number; 
/**
 * Whether the edge clears the threshold and the EV is positive.
 */
isBet: boolean }
/**
 * Build and version information for the math engine.
 */
export type EngineInfo = { 
/**
 * Version of the `bettor-core` math crate.
 */
coreVersion: string; 
/**
 * Version of this desktop shell.
 */
shellVersion: string; 
/**
 * Whether the engine was compiled with optimizations. Monte Carlo results
 * from an unoptimized build are correct but far slower.
 */
optimized: boolean }
/**
 * One point on an expected-value curve.
 */
export type EvPoint = { 
/**
 * The true win probability being assumed, 0–1.
 */
trueProb: number; 
/**
 * Expected value per unit staked at that probability.
 */
ev: number }
/**
 * What a bet is worth at a given price and true probability.
 */
export type ExpectedValue = { 
/**
 * EV as a fraction of stake. `0.05` is a 5% edge.
 */
evFraction: number; 
/**
 * EV in currency, for the stake supplied.
 */
evAmount: number; 
/**
 * Probability implied by the price taken, 0–1.
 */
impliedProb: number; 
/**
 * Win rate needed to break even at this price, 0–1. Identical to
 * [`Self::implied_prob`], named for what it means to a bettor.
 */
breakeven: number; 
/**
 * True probability minus implied probability, in probability points.
 */
edgePoints: number }
/**
 * The percentile band across all paths at one point in the season.
 */
export type FanPoint = { 
/**
 * Bets placed so far.
 */
bet: number; 
/**
 * 5th percentile bankroll.
 */
p05: number; 
/**
 * 25th percentile bankroll.
 */
p25: number; 
/**
 * Median bankroll.
 */
median: number; 
/**
 * 75th percentile bankroll.
 */
p75: number; 
/**
 * 95th percentile bankroll.
 */
p95: number }
/**
 * A game, described the way a book prices one.
 */
export type GameShape = { 
/**
 * Points the home team is expected to score.
 */
muHome: number; 
/**
 * Points the away team is expected to score.
 */
muAway: number; 
/**
 * Standard deviation of the margin.
 */
sdMargin: number; 
/**
 * Standard deviation of the combined score.
 */
sdTotal: number; 
/**
 * Whether to reweight margins onto football's key numbers.
 * 
 * Only meaningful for American football. See [`KEY_NUMBER_WEIGHTS`].
 */
keyNumbers: boolean }
/**
 * A sport as the probability visualizer models a whole game.
 * 
 * Distinct from [`LineSport`], which carries only a margin standard deviation
 * for inverting a single line. This one carries the *total's* standard
 * deviation as well, which is what makes a per-team figure and a between-team
 * correlation derivable — see [`crate::margin_model`].
 */
export type GameSport = { 
/**
 * Stable identifier, e.g. `"football"`.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * What is being scored: `"points"` or `"goals"`.
 */
unit: string; 
/**
 * Whether a normal on integers fits, or a Poisson does.
 * 
 * Low-scoring sports are Poisson-shaped and belong in
 * [`crate::match_model`]; the visualizer's normal model would misprice
 * them. Reported so the UI can send the caller to the right screen.
 */
normalModel: boolean; 
/**
 * Typical home team score.
 */
muHome: number; 
/**
 * Typical away team score.
 */
muAway: number; 
/**
 * Highest mean score the slider should offer.
 */
muMax: number; 
/**
 * Slider granularity for the means.
 */
muStep: number; 
/**
 * Standard deviation of the margin. Zero when the sport is Poisson-shaped.
 */
sdMargin: number; 
/**
 * Standard deviation of the combined score. Zero when Poisson-shaped.
 */
sdTotal: number; 
/**
 * A typical spread.
 */
spread: number; 
/**
 * Range of spreads worth charting.
 */
spreadRange: [number, number]; 
/**
 * A typical total.
 */
total: number; 
/**
 * Range of totals worth offering.
 */
totalRange: [number, number]; 
/**
 * Whether key-number reweighting applies. American football only.
 */
keyNumbers: boolean }
/**
 * A whole game, modelled and graded.
 */
export type GameView = { 
/**
 * The scoring distributions, and the team figures they imply.
 */
model: MarginModel; 
/**
 * How the spread grades.
 */
spread: SpreadGrade; 
/**
 * How the total grades.
 */
total: TotalGrade; 
/**
 * The three-way market.
 */
moneyline: Moneyline; 
/**
 * Cover probability across a range of spreads.
 */
curve: CurvePoint[] }
/**
 * A hedge on an open position.
 */
export type Hedge = { 
/**
 * Stake to place on the opposing side.
 */
hedgeStake: number; 
/**
 * Original stake plus hedge stake.
 */
totalRisk: number; 
/**
 * Net profit if the original bet wins.
 */
profitIfOriginalWins: number; 
/**
 * Net profit if the hedge wins.
 */
profitIfHedgeWins: number; 
/**
 * The worse of the two outcomes — what you are actually locking in.
 */
worstCase: number; 
/**
 * [`Self::worst_case`] as a fraction of total risk.
 */
roi: number }
/**
 * What to do about an open position when the price has moved.
 */
export type HedgeGoal = 
/**
 * Equalise the return so the outcome no longer matters.
 */
"guarantee" | 
/**
 * Stake only enough to recover the original stake if the hedge lands.
 */
"recoverStake"
/**
 * One bar of a histogram.
 */
export type HistogramBin = { 
/**
 * Left edge, inclusive.
 */
rangeStart: number; 
/**
 * Right edge, exclusive (except in the final bin).
 */
rangeEnd: number; 
/**
 * How many samples landed here.
 */
count: number; 
/**
 * [`Self::count`] as a fraction of all samples.
 */
freq: number }
/**
 * What a book is charging on a two-sided market.
 */
export type Hold = { 
/**
 * Implied probability of side A, as priced.
 */
impliedA: number; 
/**
 * Implied probability of side B, as priced.
 */
impliedB: number; 
/**
 * The two implied probabilities added together. Above 1.0 for a real book.
 */
totalImplied: number; 
/**
 * The overround as a fraction of the book: `total − 1`.
 * 
 * Negative means the two sides can be backed together for a guaranteed
 * profit. See [`Hold::is_arbitrage`].
 */
hold: number; 
/**
 * Fair probability of side A once the margin is removed proportionally.
 */
noVigProbA: number; 
/**
 * Fair probability of side B once the margin is removed proportionally.
 */
noVigProbB: number }
/**
 * The projected score line behind a spread and total.
 */
export type ImpliedScores = { 
/**
 * Points projected for the home team.
 */
home: number; 
/**
 * Points projected for the away team.
 */
away: number }
/**
 * Optimal stake under the Kelly criterion.
 */
export type Kelly = { 
/**
 * Full-Kelly fraction of bankroll. Negative means do not bet.
 */
fullFraction: number; 
/**
 * Fraction after applying the chosen Kelly multiplier.
 */
adjustedFraction: number; 
/**
 * Stake implied by [`Self::full_fraction`], floored at zero.
 */
fullStake: number; 
/**
 * Stake implied by [`Self::adjusted_fraction`], floored at zero.
 */
adjustedStake: number; 
/**
 * EV of the bet as a fraction of stake.
 */
evFraction: number; 
/**
 * True probability minus implied, in probability points.
 */
edgePoints: number }
/**
 * A priced ladder of alternate lines.
 */
export type Ladder = { 
/**
 * The true line backed out of the main market.
 */
trueLine: number; 
/**
 * One row per alternate, cheapest to longest.
 */
rows: LadderRow[]; 
/**
 * Rows omitted because the probability was beyond `[0.005, 0.995]`.
 * 
 * The TS dropped these silently.
 */
omitted: number }
/**
 * One rung of an alternate-line ladder.
 */
export type LadderRow = { 
/**
 * The alternate line.
 */
line: number; 
/**
 * Fair probability of covering it, 0–1.
 */
fairProb: number; 
/**
 * The American price that probability implies.
 */
fairOdds: number }
/**
 * One price on the breakeven ladder.
 */
export type LadderRung = { 
/**
 * American price.
 */
american: number; 
/**
 * Decimal price.
 */
decimal: number; 
/**
 * Win rate that breaks even at this price, 0–1. This is `1 / decimal`.
 */
breakeven: number; 
/**
 * Win rate needed to earn the target edge, 0–1.
 */
requiredWinRate: number; 
/**
 * Percentage points between the two above.
 * 
 * Worth its own field because it *shrinks* as the price lengthens: the
 * same 5% edge needs 2.6 points of cushion at -110 and 1.0 at +400. That
 * makes a longshot edge look easier to hit and harder to prove, which is
 * exactly backwards from how it is usually discussed.
 */
cushion: number; 
/**
 * Standard deviation of a one-unit bet at the required win rate.
 */
sdPerUnit: number; 
/**
 * Bets before the edge clears two standard errors.
 * 
 * `None` when the target edge is not positive.
 */
betsToDetect: number | null }
/**
 * A record, bet by bet and in total.
 */
export type Ledger = { 
/**
 * One entry per input bet, in the order supplied.
 */
bets: BetAnalysis[]; 
/**
 * The whole record.
 */
summary: LedgerSummary }
/**
 * A real record, reshaped into the input the variance module takes.
 */
export type LedgerMix = { 
/**
 * One leg per price bucket, shortest price first.
 */
legs: MixLeg[]; 
/**
 * Bets that contributed.
 */
betsUsed: number; 
/**
 * Bets skipped because no fair closing line was recorded for them.
 * 
 * Reported rather than quietly dropped: a mix built from a third of a
 * record is a different claim than one built from all of it.
 */
betsSkipped: number }
/**
 * A whole betting record, summarised.
 */
export type LedgerSummary = { 
/**
 * Bets in the record.
 */
bets: number; 
/**
 * Bets that have settled.
 */
settled: number; 
/**
 * Bets still open.
 */
pending: number; 
/**
 * Bets won.
 */
won: number; 
/**
 * Bets lost.
 */
lost: number; 
/**
 * Bets pushed or voided.
 */
pushed: number; 
/**
 * Money risked on settled bets.
 */
staked: number; 
/**
 * Realised profit.
 */
profit: number; 
/**
 * Profit as a fraction of money risked.
 */
roi: number; 
/**
 * Share of *decided* bets won, 0–1. Pushes excluded.
 */
winRate: number; 
/**
 * Settled bets that also have a closing price recorded.
 */
withClose: number; 
/**
 * Mean probability points gained against the close.
 * 
 * `None` when no bet in the record has a closing price.
 */
meanClvPoints: number | null; 
/**
 * Share of those bets that beat the close, 0–1.
 */
beatCloseRate: number | null; 
/**
 * Settled bets whose closing market was recorded on both sides.
 */
withFairClose: number; 
/**
 * Profit the record should have produced, against the fair close.
 * 
 * `None` when no bet has both closing prices.
 */
expectedProfit: number | null; 
/**
 * Expected profit as a fraction of the money those bets risked.
 */
expectedRoi: number | null; 
/**
 * Realised profit minus expected profit.
 * 
 * Variance, named. Positive means the record ran better than the prices
 * it took deserved; negative means worse. It is normally the largest
 * number on this list, and treating it as skill in either direction is
 * the most common way a betting record is misread.
 */
luck: number | null }
/**
 * Which of two competing lines is better, and by how much.
 */
export type LineComparison = { 
/**
 * True line implied by the first quote.
 */
trueLineA: number; 
/**
 * True line implied by the second quote.
 */
trueLineB: number; 
/**
 * Which is better: `None` for a tie.
 */
better: Side | null; 
/**
 * Distance between the two implied true lines, in points.
 */
diff: number }
/**
 * Scoring variance for one sport, and the markets it posts.
 */
export type LineSport = { 
/**
 * Stable identifier, e.g. `"nba"`.
 */
key: string; 
/**
 * Display name, e.g. `"NBA"`.
 */
label: string; 
/**
 * Standard deviation of the margin of victory, in points.
 */
spreadStd: number; 
/**
 * Standard deviation of the game total, in points.
 */
totalStd: number; 
/**
 * Which markets this sport is usually priced on.
 */
markets: Market[]; 
/**
 * True where a draw is a distinct moneyline outcome.
 */
threeWayMoneyline: boolean }
/**
 * Something went wrong talking to the bet log.
 * 
 * Deliberately separate from `MathError`: a disk failure and a bad
 * probability are not the same kind of problem, and collapsing them would
 * leave the UI unable to tell the user which one happened.
 */
export type LogError = 
/**
 * The database could not be read or written.
 */
{ kind: "storage"; detail: { 
/**
 * What SQLite reported.
 */
message: string } } | 
/**
 * No bet with that id.
 */
{ kind: "notFound"; detail: { 
/**
 * The id that was looked up.
 */
id: number } } | 
/**
 * A field failed validation before it could be stored.
 */
{ kind: "invalid"; detail: { 
/**
 * Which field.
 */
field: string; 
/**
 * Why it was rejected.
 */
reason: string } }
/**
 * A scoring model, as distributions over integers.
 */
export type MarginModel = { 
/**
 * Home score distribution.
 */
homeScores: PmfPoint[]; 
/**
 * Away score distribution.
 */
awayScores: PmfPoint[]; 
/**
 * Margin distribution, home minus away.
 */
margin: PmfPoint[]; 
/**
 * Combined score distribution.
 */
total: PmfPoint[]; 
/**
 * Standard deviation of the margin, as supplied.
 */
sdMargin: number; 
/**
 * Standard deviation of the total, as supplied.
 */
sdTotal: number; 
/**
 * Per-team standard deviation implied by the two above.
 */
sdTeam: number; 
/**
 * Correlation between the two teams' scores, implied by the two above.
 * 
 * Negative means game script pulls the scores apart — one team runs the
 * clock out while the other throws. Positive means shared pace.
 */
impliedCorrelation: number; 
/**
 * Mean margin of the distribution, after any key-number reweighting.
 */
meanMargin: number; 
/**
 * Mean total.
 */
meanTotal: number }
/**
 * A precision-weighted combination of two margin estimates.
 */
export type MarginPosterior = { 
/**
 * Posterior expected margin.
 */
margin: number; 
/**
 * The same figure as a spread, which is its negation.
 */
spread: number; 
/**
 * Posterior standard deviation. Always below both inputs — combining two
 * estimates cannot make you less certain.
 */
stdDev: number; 
/**
 * Share of the posterior mean contributed by the market, 0–1.
 */
marketWeight: number }
/**
 * Which market the two positions sit on.
 */
export type Market = 
/**
 * A point spread. Lines are folded onto the favorite's margin axis, so
 * `-3.5` and `+3.5` describe the same number.
 */
"spread" | 
/**
 * A total. Lines are used as posted.
 */
"total"
/**
 * Every market derivable from a score matrix.
 */
export type MarketProbs = { 
/**
 * Probability the home side wins outright.
 */
homeWin: number; 
/**
 * Probability of a draw. Zero when draws were redistributed.
 */
draw: number; 
/**
 * Probability the away side wins outright.
 */
awayWin: number; 
/**
 * The ten most likely exact scorelines, most likely first.
 */
topScorelines: Scoreline[]; 
/**
 * Cover probabilities at each requested spread.
 */
spreads: SpreadProb[]; 
/**
 * Over/under probabilities at each requested total.
 */
totals: TotalProb[] }
/**
 * Markets derived from a scoreline model, plus the grid's truncation mass.
 */
export type MatchMarkets = { 
/**
 * Moneyline, spreads, totals, and top scorelines.
 */
markets: MarketProbs; 
/**
 * Probability that fell outside the grid before renormalising.
 * 
 * A large value means `max_score` is too low for these scoring rates.
 */
truncationMass: number }
/**
 * How a match model was parameterised.
 */
export type MatchModel = 
/**
 * Independent Poisson scoring.
 */
{ kind: "poisson"; lambda_home: number; lambda_away: number } | 
/**
 * Overdispersed scoring, for blowout-prone matchups.
 */
{ kind: "negativeBinomial"; mean_home: number; mean_away: number; r_home: number; r_away: number }
/**
 * Scoring rates and line menus for the match models.
 */
export type MatchSport = { 
/**
 * Stable identifier, e.g. `"soccer"`.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * What a unit of scoring is called — "Goals", "Runs".
 */
scoreLabel: string; 
/**
 * Typical home scoring rate.
 */
defaultHome: number; 
/**
 * Typical away scoring rate.
 */
defaultAway: number; 
/**
 * Negative binomial dispersion. Smaller means more overdispersed.
 */
defaultR: number; 
/**
 * Guidance on choosing `r`, shown beside the input.
 */
rHint: string; 
/**
 * Largest score the matrix is evaluated to.
 * 
 * Truncating drops real probability mass — see
 * [`crate::match_model::MatchMarkets::truncation_mass`], which reports
 * how much, so this can be checked rather than assumed.
 */
maxScore: number; 
/**
 * Spread lines worth pricing.
 */
spreadLines: number[]; 
/**
 * Total lines worth pricing.
 */
totalLines: number[]; 
/**
 * True where a draw is a possible result.
 */
allowDraw: boolean }
/**
 * Errors produced by invalid input to a math routine.
 * 
 * The TypeScript returns `null` on bad input, which collapses "you typed a
 * letter", "that probability is out of range", and "this solver did not
 * converge" into one indistinguishable value. Each gets its own variant here
 * so the UI can say something useful.
 */
export type MathError = 
/**
 * A string input could not be parsed in the expected odds format.
 */
{ kind: "parseOdds"; detail: { 
/**
 * The offending input, echoed back so the UI can highlight it.
 */
value: string; 
/**
 * The format that was expected: `"american"`, `"decimal"`, `"fractional"`.
 */
format: string } } | 
/**
 * A probability fell outside the range a routine accepts.
 */
{ kind: "probabilityOutOfRange"; detail: { 
/**
 * The probability that was rejected.
 */
value: number; 
/**
 * Why it was rejected, e.g. `"must be strictly between 0 and 1"`.
 */
reason: string } } | 
/**
 * A numeric argument was outside the domain the routine accepts.
 */
{ kind: "domainError"; detail: { 
/**
 * Name of the parameter, matching the public API's argument name.
 */
param: string; 
/**
 * The constraint that was violated, e.g. `"greater than zero"`.
 */
constraint: string; 
/**
 * The value supplied.
 */
value: number } } | 
/**
 * A collection argument had the wrong shape (too few legs, mismatched lengths).
 */
{ kind: "shapeError"; detail: { 
/**
 * What was being counted, e.g. `"parlay legs"`.
 */
what: string; 
/**
 * The requirement, e.g. `"at least 2"`.
 */
expected: string; 
/**
 * The count actually supplied.
 */
got: number } } | 
/**
 * An iterative solver ran out of iterations without meeting its tolerance.
 * 
 * Reported rather than swallowed: a devig method that silently returns its
 * last un-converged iterate is worse than one that admits it failed.
 */
{ kind: "noConvergence"; detail: { 
/**
 * Which solver gave up, e.g. `"shin"`.
 */
solver: string; 
/**
 * The iteration cap it hit.
 */
iterations: number; 
/**
 * How far from tolerance it still was when it stopped.
 */
residual: number } }
/**
 * A middle or trap, priced.
 */
export type Middle = { 
/**
 * True when the gap wins both tickets, false when it loses both.
 */
isMiddle: boolean; 
/**
 * Width of the gap between the two numbers.
 */
gapSize: number; 
/**
 * Probability the result lands inside the gap, 0–1.
 */
gapProb: number; 
/**
 * Market's expected value on the shared axis — the favorite's expected
 * margin, or the expected total.
 */
trueCenter: number; 
/**
 * Expected profit in currency.
 */
ev: number; 
/**
 * [`Self::ev`] as a fraction of everything staked.
 */
evFraction: number; 
/**
 * Total staked across both tickets.
 */
totalStaked: number; 
/**
 * Every way this resolves. Probabilities sum to 1.
 */
outcomes: Outcome[] }
/**
 * One side of the position.
 * 
 * Named for the direction that wins it rather than the team it is on, which
 * is what stops the two legs drifting into different sign conventions.
 */
export type MiddleLeg = { 
/**
 * The number bet, as posted.
 */
line: number; 
/**
 * Fair (devigged) probability this leg covers — see
 * [`crate::line::fair_cover_prob`].
 */
fairCoverProb: number; 
/**
 * Amount staked.
 */
stake: number; 
/**
 * Decimal price taken.
 */
decimalOdds: number }
/**
 * One kind of bet in a mix: a price, a stake, an edge, and how many of them.
 */
export type MixLeg = { 
/**
 * American price.
 */
american: number; 
/**
 * Stake on each bet of this kind.
 */
stake: number; 
/**
 * EV per unit staked, as a fraction. `0.03` is a 3% edge.
 */
edge: number; 
/**
 * How many bets of this kind the mix contains.
 */
count: number }
/**
 * What one kind of bet contributes to the mix.
 */
export type MixLegResult = { 
/**
 * American price, normalised.
 */
american: number; 
/**
 * Decimal price.
 */
decimal: number; 
/**
 * How many bets of this kind, echoed back from the input.
 * 
 * Carried on the row rather than left to the caller to line up against
 * its own input list: a leg the caller skipped shifts every index after
 * it, and a table that reads counts from one list and prices from another
 * would mislabel every row without failing.
 */
count: number; 
/**
 * Win rate implied by this leg's price and edge, 0–1.
 */
winProb: number; 
/**
 * Win rate that would break even at this price, 0–1.
 */
breakeven: number; 
/**
 * Total staked on bets of this kind.
 */
totalStake: number; 
/**
 * Share of the mix's money, 0–1.
 */
stakeShare: number; 
/**
 * Expected profit from bets of this kind.
 */
ev: number; 
/**
 * Share of the mix's *variance*, 0–1.
 * 
 * The number the whole builder is for. Variance scales with the square of
 * the stake and with the length of the price, so a price bucket routinely
 * contributes a share of the swing several times its share of the money.
 */
varianceShare: number }
/**
 * The three-way market a margin distribution implies.
 */
export type Moneyline = { 
/**
 * Probability the home team wins outright, 0–1.
 */
home: number; 
/**
 * Probability of a level score, 0–1.
 * 
 * In football and basketball this is a regulation tie, not a settled
 * draw — those sports play overtime. In soccer it is the draw itself.
 */
draw: number; 
/**
 * Probability the away team wins outright, 0–1.
 */
away: number }
/**
 * The three ways a price gets written.
 */
export type OddsFormat = 
/**
 * `-110`, `+250`.
 */
"american" | 
/**
 * `1.909`, `3.5`.
 */
"decimal" | 
/**
 * `10/11`, `5/2`.
 */
"fractional"
/**
 * A decimal price expressed every other way.
 */
export type OddsView = { 
/**
 * American price, e.g. `-110`.
 */
american: number; 
/**
 * Fractional numerator, e.g. `10` in `10/11`.
 */
fractionalNum: number; 
/**
 * Fractional denominator, e.g. `11` in `10/11`.
 */
fractionalDen: number; 
/**
 * Implied probability on a **0–1** scale (the TS used 0–100 here).
 */
probability: number }
/**
 * One way the position can resolve.
 */
export type Outcome = { 
/**
 * What happened, for display.
 */
label: string; 
/**
 * Probability of it, 0–1.
 */
probability: number; 
/**
 * Net profit across both tickets if it happens.
 */
netProfit: number }
/**
 * A priced parlay.
 */
export type Parlay = { 
/**
 * Combined decimal price — the product of every leg.
 */
decimal: number; 
/**
 * Combined probability implied, 0–1, assuming independence.
 */
impliedProb: number; 
/**
 * Return if every leg lands, stake included.
 */
payout: number; 
/**
 * Return minus stake.
 */
profit: number; 
/**
 * How many legs were priced.
 */
legCount: number }
/**
 * One integer outcome and its probability.
 */
export type PmfPoint = { 
/**
 * The score, margin, or total.
 */
k: number; 
/**
 * Probability of exactly that value, 0–1.
 */
p: number }
/**
 * One position within a sport.
 */
export type PropPosition = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Stats commonly posted for this position.
 */
stats: PropStat[] }
/**
 * A prop simulation: samples, summarised.
 */
export type PropSimulation = { 
/**
 * Seed that produced this run. Pass it back to reproduce exactly.
 * 
 * A decimal string, not a number — see `resolve_seed`.
 */
seed: string; 
/**
 * Binned samples, ready to chart.
 */
histogram: HistogramBin[]; 
/**
 * Mean and standard deviation of the sample.
 */
stats: Stats; 
/**
 * Probability the prop goes over the line, 0–1.
 */
overProb: number; 
/**
 * Probability it does not, 0–1.
 * 
 * Both sides come back counted from `bettor_core`; neither is derived
 * from the other here. See `distributions::over_under_prob`.
 */
underProb: number; 
/**
 * Fair American price for the over.
 */
overFairOdds: number; 
/**
 * Fair American price for the under.
 */
underFairOdds: number }
/**
 * Prop presets for one sport.
 */
export type PropSport = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Positions this sport prices props for.
 */
positions: PropPosition[] }
/**
 * One prop market, and the distribution that fits its shape.
 */
export type PropStat = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * The distribution this stat is simulated from.
 */
distribution: Distribution; 
/**
 * A typical projection.
 */
defaultProjection: number; 
/**
 * A typical posted line.
 */
defaultLine: number; 
/**
 * What the numbers are measured in.
 */
unit: string }
/**
 * A regressed estimate with its uncertainty.
 */
export type Regressed = { 
/**
 * Shrinkage-adjusted estimate of true talent.
 */
estimate: number; 
/**
 * Weight the observed sample earned, 0–1.
 */
weight: number; 
/**
 * Lower bound of the 90% interval.
 */
lower: number; 
/**
 * Upper bound of the 90% interval.
 */
upper: number }
/**
 * Regression presets for one sport.
 */
export type RegressionSport = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Stats with published regression constants.
 */
stats: RegressionStat[] }
/**
 * One regressable stat.
 */
export type RegressionStat = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Sample size at which observed and league average carry equal weight.
 */
regressionConstant: number; 
/**
 * The population mean this stat regresses toward.
 */
leagueAverage: number; 
/**
 * An illustrative hot-start observation.
 */
defaultObserved: number; 
/**
 * An illustrative sample size.
 */
defaultSampleSize: number; 
/**
 * What the stat is measured in.
 */
unit: string; 
/**
 * What the sample is counted in — plate appearances, shots, attempts.
 */
sampleUnit: string }
/**
 * Parameters for a survival simulation.
 */
export type RuinInput = { 
/**
 * True win probability, 0–1.
 */
winProb: number; 
/**
 * Decimal price of each bet.
 */
decimalOdds: number; 
/**
 * Flat stake per bet.
 */
betSize: number; 
/**
 * Starting bankroll.
 */
bankroll: number; 
/**
 * How many bets to simulate.
 */
numBets: number; 
/**
 * How many independent paths to run.
 */
numSims: number }
/**
 * Outcome of a survival simulation.
 */
export type RuinResult = { 
/**
 * Seed that produced this run. Feed it back to reproduce exactly.
 * 
 * Crosses the wire as a decimal string — see [`crate::seed_repr`].
 */
seed: string; 
/**
 * Fraction of paths that went broke, 0–1.
 */
ruinProb: number; 
/**
 * EV of a single bet, in currency.
 */
evPerBet: number; 
/**
 * EV as a fraction of stake.
 */
edge: number; 
/**
 * Median ending bankroll across **all** paths, ruined counted as zero.
 */
medianEndingAll: number; 
/**
 * Mean ending bankroll across **all** paths, ruined counted as zero.
 */
meanEndingAll: number; 
/**
 * Median ending bankroll across **surviving** paths only.
 * 
 * This is the figure the TS labelled simply "median bankroll", beside a
 * mean computed over a different population.
 */
medianEndingSurvivors: number; 
/**
 * Mean of each path's worst peak-to-trough drop, as a fraction of peak.
 */
meanMaxDrawdown: number; 
/**
 * Median of the same, which is the more honest summary of a skewed figure.
 */
medianMaxDrawdown: number; 
/**
 * Longest run of consecutive losses seen in any path.
 * 
 * Not in the TS, and the statistic bettors most underestimate at long
 * prices: a real 21% shot loses more than twenty in a row routinely.
 */
longestLosingStreak: number; 
/**
 * Solvency over time, for charting.
 */
survivalCurve: SurvivalPoint[] }
/**
 * One exact scoreline and its probability.
 */
export type Scoreline = { 
/**
 * Home team's score.
 */
home: number; 
/**
 * Away team's score.
 */
away: number; 
/**
 * Probability of exactly this result.
 */
prob: number }
/**
 * A season to simulate: a bet mix, a bankroll, and a number of runs.
 */
export type SeasonInput = { 
/**
 * The bets that make up one season. Their counts set its length.
 */
legs: MixLeg[]; 
/**
 * Starting bankroll.
 */
bankroll: number; 
/**
 * How many independent seasons to run.
 */
numSims: number; 
/**
 * Whether a bankroll that cannot cover the next stake stops the season.
 * 
 * Off by default in the UI: the fan chart is about the shape of an
 * ordinary year, and a ruin barrier truncates exactly the paths that make
 * the point. [`crate::risk_of_ruin`] is the module for the barrier.
 * 
 * With it off the season plays every bet regardless, so a path may finish
 * below zero. That is deliberate — it keeps the fan an unbiased picture of
 * the profit distribution instead of one censored at the bottom — but it
 * means a negative ending is a bookkeeping figure, not a real bankroll.
 * [`SeasonResult::ruin_prob`] still reports how often it happened.
 */
stopAtRuin: boolean }
/**
 * What a season looked like across every simulated run.
 */
export type SeasonResult = { 
/**
 * Seed that produced this run. Feed it back to reproduce exactly.
 * 
 * Crosses the wire as a decimal string — see [`crate::seed_repr`].
 */
seed: string; 
/**
 * Bets in one season.
 */
bets: number; 
/**
 * Bankroll every season started from.
 * 
 * Echoed back because it is the line between a winning year and a losing
 * one: a chart that drew that line from a live input field would move it
 * the moment the field was edited, and quietly relabel a finished run.
 */
startingBankroll: number; 
/**
 * The closed-form summary of the same mix, for comparison with the fan.
 */
mix: BetMix; 
/**
 * Percentile bands over the season, for the fan chart.
 */
fan: FanPoint[]; 
/**
 * Fraction of seasons that ended below the starting bankroll, 0–1.
 * 
 * The headline. A real edge loses money over a season far more often than
 * people expect, and the figure grows with the length of the prices.
 */
losingSeasonProb: number; 
/**
 * Fraction of seasons that could not cover a stake at some point, 0–1.
 */
ruinProb: number; 
/**
 * 5th percentile ending bankroll.
 */
endingP05: number; 
/**
 * Median ending bankroll.
 */
endingMedian: number; 
/**
 * 95th percentile ending bankroll.
 */
endingP95: number; 
/**
 * Mean ending bankroll. Compare with the median: the gap is the skew.
 */
endingMean: number; 
/**
 * Median worst peak-to-trough drop, as a fraction of the peak.
 */
medianMaxDrawdown: number; 
/**
 * 95th percentile of the same — the bad-but-not-unthinkable year.
 */
p95MaxDrawdown: number; 
/**
 * Longest run of consecutive losses seen in any season.
 */
longestLosingStreak: number }
/**
 * Identifies one of two compared quotes.
 */
export type Side = 
/**
 * The first quote.
 */
"a" | 
/**
 * The second quote.
 */
"b"
/**
 * Everything the frontend needs to populate its sport pickers.
 */
export type SportConfig = { 
/**
 * Scoring spreads for line inversion and alternate-line ladders.
 */
lines: LineSport[]; 
/**
 * Scoring rates for the match models.
 */
matches: MatchSport[]; 
/**
 * Player prop presets, by sport and position.
 */
props: PropSport[]; 
/**
 * Regression constants and league averages, by sport and stat.
 */
regression: RegressionSport[]; 
/**
 * Whole-game scoring shapes for the probability visualizer.
 */
games: GameSport[] }
/**
 * How a spread grades against a margin distribution.
 */
export type SpreadGrade = { 
/**
 * The line, from the home team's perspective. `-3.5` means laying 3.5.
 */
spread: number; 
/**
 * Probability the home side covers, 0–1.
 */
homeCovers: number; 
/**
 * Probability of a push, 0–1. Always zero on a half-point line.
 */
push: number; 
/**
 * Probability the away side covers, 0–1.
 */
awayCovers: number }
/**
 * Cover probabilities for one spread.
 */
export type SpreadProb = { 
/**
 * The line, from the home side's perspective.
 */
spread: number; 
/**
 * Probability the home side covers.
 */
homeCovers: number; 
/**
 * Probability the away side covers.
 */
awayCovers: number; 
/**
 * Probability of a push. Nonzero only on whole-number lines.
 * 
 * The TS dropped this mass entirely, so the two sides did not sum to 1.
 */
push: number }
/**
 * Mean and standard deviation of a sample.
 */
export type Stats = { 
/**
 * Sample mean.
 */
mean: number; 
/**
 * Sample standard deviation, using the `n − 1` denominator.
 */
stdDev: number }
/**
 * Fraction of paths still solvent at a given bet number.
 */
export type SurvivalPoint = { 
/**
 * Bet index.
 */
bet: number; 
/**
 * Fraction of paths still able to place a bet, 0–1.
 */
survival: number }
/**
 * A complete teaser, priced.
 */
export type Teaser = { 
/**
 * Per-leg analysis, in the order supplied.
 */
legs: TeaserLegAnalysis[]; 
/**
 * Probability every leg covers, assuming independence.
 */
combinedProb: number; 
/**
 * American price that probability implies.
 */
fairOdds: number; 
/**
 * Win rate needed to break even at the price offered, 0–1.
 */
breakeven: number; 
/**
 * Expected value as a fraction of stake.
 */
evFraction: number; 
/**
 * True when any leg crosses a key number, meaning the normal model is
 * understating this teaser's true value.
 */
modelIgnoresKeyNumbers: boolean }
/**
 * One leg of a teaser, as posted.
 */
export type TeaserLeg = { 
/**
 * The spread before teasing, in the bettor's favour when positive.
 */
spread: number; 
/**
 * Fair (devigged) probability of covering that spread — see
 * [`crate::line::fair_cover_prob`].
 */
fairCoverProb: number }
/**
 * One leg, priced after the points are applied.
 */
export type TeaserLegAnalysis = { 
/**
 * The spread as posted.
 */
spread: number; 
/**
 * The spread after the teaser points are added.
 */
teasedSpread: number; 
/**
 * True line backed out of the posted spread and its fair price.
 */
trueLine: number; 
/**
 * Probability of covering the teased spread, 0–1.
 */
coverProb: number; 
/**
 * The American price that probability implies.
 */
fairOdds: number; 
/**
 * Key numbers the tease moves through.
 * 
 * Reported for judgement, **not** priced in — see the module docs.
 */
keyNumbersCrossed: number[] }
/**
 * How a total grades.
 */
export type TotalGrade = { 
/**
 * The line.
 */
total: number; 
/**
 * Probability of the over, 0–1.
 */
over: number; 
/**
 * Probability of a push, 0–1.
 */
push: number; 
/**
 * Probability of the under, 0–1.
 */
under: number }
/**
 * Over/under probabilities for one total.
 */
export type TotalProb = { 
/**
 * The line.
 */
line: number; 
/**
 * Probability the total goes over.
 */
over: number; 
/**
 * Probability the total stays under.
 */
under: number; 
/**
 * Probability of a push.
 */
push: number }
/**
 * Which side of a total.
 */
export type TotalSide = 
/**
 * Betting the game goes over.
 */
"over" | 
/**
 * Betting the game stays under.
 */
"under"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
