// AUTO-GENERATED by `cargo test -p bettor-desktop`. Do not edit.
// Source of truth: src-tauri/src/commands.rs

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Reports the math engine's version.
 */
async engineInfo() : Promise<EngineInfo> {
    return await TAURI_INVOKE("engine_info");
},
/**
 * Converts a price in any format to decimal odds.
 */
async toDecimal(value: string, format: OddsFormat) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("to_decimal", { value, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expresses a decimal price in every other format.
 */
async fromDecimal(decimal: number) : Promise<Result<OddsView, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("from_decimal", { decimal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Converts a probability to the American price implying it.
 */
async impliedToAmerican(prob: number) : Promise<number> {
    return await TAURI_INVOKE("implied_to_american", { prob });
},
/**
 * Converts a probability to the decimal price implying it.
 * 
 * The frontend needs this to show fair odds beside a devigged or modelled
 * probability. It cannot compute `1 / p` itself — that is math, and math
 * lives in the core.
 */
async impliedToDecimal(prob: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("implied_to_decimal", { prob }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Computes the hold on a two-sided market.
 */
async calculateHold(impliedA: number, impliedB: number) : Promise<Result<Hold, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_hold", { impliedA, impliedB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ranks books on the same market by hold, cheapest first.
 * 
 * Rows that fail validation are kept with their error rather than dropped, so
 * a book never silently vanishes from the table.
 */
async compareVig(books: BookInput[]) : Promise<BookRow[]> {
    return await TAURI_INVOKE("compare_vig", { books });
},
/**
 * Runs every devig method against a market.
 */
async devigAll(impliedProbs: number[]) : Promise<DevigRow[]> {
    return await TAURI_INVOKE("devig_all", { impliedProbs });
},
/**
 * Total implied probability of a market, before any devig.
 */
async marketOverround(impliedProbs: number[]) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("market_overround", { impliedProbs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Completes a partially-entered set of probabilities with the leftover one.
 */
async completeSimplex(partial: number[]) : Promise<Result<number[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_simplex", { partial }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expected value of a bet against a fair probability.
 */
async evVsFair(fairProb: number, betImplied: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ev_vs_fair", { fairProb, betImplied }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expected value of a bet at a price and true probability.
 */
async expectedValue(decimal: number, trueProb: number, stake: number) : Promise<Result<ExpectedValue, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("expected_value", { decimal, trueProb, stake }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kelly stake for a price, probability, and bankroll.
 */
async kelly(decimal: number, trueProb: number, bankroll: number, multiplier: number) : Promise<Result<Kelly, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kelly", { decimal, trueProb, bankroll, multiplier }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Splits a bankroll across every outcome of an arbitrage.
 */
async arbitrage(decimals: number[], totalStake: number) : Promise<Result<Arbitrage, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("arbitrage", { decimals, totalStake }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sizes a hedge against an open position.
 */
async hedge(originalStake: number, originalDecimal: number, hedgeDecimal: number, goal: HedgeGoal) : Promise<Result<Hedge, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hedge", { originalStake, originalDecimal, hedgeDecimal, goal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a parlay from its legs.
 */
async parlay(legs: number[], stake: number) : Promise<Result<Parlay, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parlay", { legs, stake }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Closing line value, measured every way that is defensible.
 */
async clv(betDecimal: number, closeDecimal: number, opposingCloseDecimal: number | null) : Promise<Result<Clv, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clv", { betDecimal, closeDecimal, opposingCloseDecimal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the vig from a two-sided market.
 */
async fairCoverProb(american: number, opposingAmerican: number) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fair_cover_prob", { american, opposingAmerican }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the market's true line out of a posted line and a fair probability.
 */
async impliedTrueLine(lineValue: number, fairCoverProb: number, stdDev: number, betType: BetType) : Promise<Result<number, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("implied_true_line", { lineValue, fairCoverProb, stdDev, betType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices every alternate line around a main line.
 */
async generateLadder(mainLine: number, fairCoverProb: number, stdDev: number, betType: BetType, range: number, step: number) : Promise<Result<Ladder, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_ladder", { mainLine, fairCoverProb, stdDev, betType, range, step }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compares two line-and-price quotes on the same market.
 */
async compareLines(lineA: number, fairProbA: number, lineB: number, fairProbB: number, stdDev: number, betType: BetType) : Promise<Result<LineComparison, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_lines", { lineA, fairProbA, lineB, fairProbB, stdDev, betType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Splits a total around a spread into each side's projected score.
 */
async impliedScores(spread: number, total: number) : Promise<Result<ImpliedScores, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("implied_scores", { spread, total }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every sport preset the frontend populates its pickers from.
 * 
 * Returned from the core rather than re-declared in TypeScript: a
 * mistranscribed σ or regression constant is invisible in a unit test and
 * wrong in every number the calculator prints.
 */
async sportConfig() : Promise<SportConfig> {
    return await TAURI_INVOKE("sport_config");
},
/**
 * Prices every market implied by a scoreline model.
 */
async deriveMarkets(model: MatchModel, maxScore: number, spreadLines: number[], totalLines: number[], allowDraw: boolean) : Promise<Result<MatchMarkets, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("derive_markets", { model, maxScore, spreadLines, totalLines, allowDraw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Regresses a rate toward a baseline and attaches a 90% interval.
 */
async regress(observed: number, baseline: number, sampleSize: number, regressionConstant: number) : Promise<Result<Regressed, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("regress", { observed, baseline, sampleSize, regressionConstant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Traces how a regressed estimate converges as the sample grows.
 */
async convergenceSeries(observed: number, baseline: number, regressionConstant: number, maxSample: number, steps: number) : Promise<Result<ConvergencePoint[], MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convergence_series", { observed, baseline, regressionConstant, maxSample, steps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a middle or trap.
 */
async calculateMiddle(market: Market, highSide: MiddleLeg, lowSide: MiddleLeg, stdDev: number) : Promise<Result<Middle, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_middle", { market, highSide, lowSide, stdDev }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a teaser against the book's offered number.
 */
async analyzeTeaser(legs: TeaserLeg[], teaserPoints: number, teaserDecimalOdds: number, stdDev: number) : Promise<Result<Teaser, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_teaser", { legs, teaserPoints, teaserDecimalOdds, stdDev }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a parlay whose legs move together.
 */
async correlatedParlay(probs: number[], correlation: number, seed: string | null, sims: number | null) : Promise<Result<Correlated, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correlated_parlay", { probs, correlation, seed, sims }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Folds a model probability into a market probability.
 */
async betaUpdate(marketProb: number, modelProb: number, marketN: number, modelN: number) : Promise<Result<BetaPosterior, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("beta_update", { marketProb, modelProb, marketN, modelN }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Folds a model into a market across three or more outcomes.
 */
async dirichletUpdate(marketProbs: number[], modelProbs: number[], marketN: number, modelN: number) : Promise<Result<DirichletPosterior, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dirichlet_update", { marketProbs, modelProbs, marketN, modelN }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Combines a market margin and a model margin by precision.
 */
async marginUpdate(marketMargin: number, modelMargin: number, marketStd: number, modelStd: number) : Promise<Result<MarginPosterior, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("margin_update", { marketMargin, modelMargin, marketStd, modelStd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prices a posterior probability against an available quote.
 */
async edgeVsPrice(posteriorProb: number, decimalOdds: number, threshold: number) : Promise<Result<Edge, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edge_vs_price", { posteriorProb, decimalOdds, threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Simulates a player prop and prices both sides of the line.
 * 
 * Long-running, so it is `async`: Tauri runs `async` commands off the main
 * thread and the window keeps painting.
 */
async simulateProp(n: number, distribution: Distribution, mu: number, varMultiplier: number, lineValue: number, seed: string | null) : Promise<Result<PropSimulation, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulate_prop", { n, distribution, mu, varMultiplier, lineValue, seed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Simulates bankroll survival under flat betting.
 * 
 * Long-running, so it is `async` for the same reason as [`simulate_prop`].
 */
async simulateRuin(input: RuinInput, seed: string | null) : Promise<Result<RuinResult, MathError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulate_ruin", { input, seed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Standard normal CDF, exposed for charting the model directly.
 */
async normalCdf(z: number) : Promise<number> {
    return await TAURI_INVOKE("normal_cdf", { z });
},
/**
 * Converts a win probability to the point spread implying it.
 */
async probToSpread(p: number, stdDev: number) : Promise<number> {
    return await TAURI_INVOKE("prob_to_spread", { p, stdDev });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * An arbitrage opportunity, or the absence of one.
 */
export type Arbitrage = { 
/**
 * Per-outcome stakes, in the order supplied.
 */
legs: ArbitrageLeg[]; 
/**
 * Implied probabilities summed. Below 1.0 means free money.
 */
totalImplied: number; 
/**
 * Profit locked in whichever outcome lands. Negative when not an arb.
 */
profit: number; 
/**
 * [`Self::profit`] as a fraction of total stake.
 */
roi: number }
/**
 * Stake and payout for one leg of an arbitrage.
 */
export type ArbitrageLeg = { 
/**
 * Decimal price for this outcome.
 */
decimal: number; 
/**
 * Probability it implies, 0–1.
 */
implied: number; 
/**
 * Stake to place on it.
 */
stake: number; 
/**
 * Return if it wins, stake included.
 */
payout: number }
/**
 * Which kind of line is being modelled.
 */
export type BetType = 
/**
 * A point spread.
 */
"spread" | 
/**
 * A total, with a side.
 */
{ total: TotalSide }
/**
 * A Beta posterior over a two-way market.
 */
export type BetaPosterior = { 
/**
 * Prior successes, from the market.
 */
priorAlpha: number; 
/**
 * Prior failures, from the market.
 */
priorBeta: number; 
/**
 * Posterior successes, after folding in the model.
 */
posteriorAlpha: number; 
/**
 * Posterior failures.
 */
posteriorBeta: number; 
/**
 * Posterior probability of the first side, 0–1.
 */
posteriorProb: number; 
/**
 * How far the posterior moved off the market, in probability points.
 * 
 * This is the number to sanity-check: a model that drags a liquid market
 * several points is more likely miscalibrated than right.
 */
shiftFromMarket: number }
/**
 * One book's quote in a vig comparison.
 */
export type BookInput = { 
/**
 * Book name, carried through to the result.
 */
name: string; 
/**
 * Implied probability of side A.
 */
impliedA: number; 
/**
 * Implied probability of side B.
 */
impliedB: number }
/**
 * One row of a vig comparison.
 * 
 * Exactly one of `hold` and `error` is set. Failed rows are kept rather than
 * dropped so a book never silently vanishes from the table.
 */
export type BookRow = { 
/**
 * Book name.
 */
name: string; 
/**
 * The hold it charges, when the quote could be read.
 */
hold: Hold | null; 
/**
 * Why the quote could not be read, when it could not.
 */
error: MathError | null }
/**
 * Closing line value, measured every way that is defensible.
 */
export type Clv = { 
/**
 * Decimal price taken.
 */
betDecimal: number; 
/**
 * Decimal price at the close.
 */
closeDecimal: number; 
/**
 * Probability implied by the price taken, 0–1.
 */
betImplied: number; 
/**
 * Probability implied by the closing price, 0–1. Still contains vig.
 */
closeImplied: number; 
/**
 * `bet/close - 1`. What the TS called CLV, EV, and "cents" alike.
 * 
 * Retained for continuity with the web app, but it is a ratio of prices
 * and should never be compared across different price levels.
 */
ratio: number; 
/**
 * Probability points gained: `close_implied - bet_implied`.
 * 
 * The measure that survives comparison across price levels. Positive
 * means the market moved toward your side after you bet.
 */
probPoints: number; 
/**
 * American cents the line moved, which is what people actually quote.
 * 
 * Reported alongside [`Self::prob_points`] precisely so the gap between
 * the two is visible: fifty cents on a longshot is worth less than twenty
 * on a favorite.
 */
cents: number; 
/**
 * EV against the raw closing price — vig included, so overstated.
 * 
 * This is the number the web app reported as "Expected Value".
 */
evVsRawClose: number; 
/**
 * EV against the devigged closing price.
 * 
 * `None` when the opposing closing price was not supplied, because
 * without it the vig cannot be removed and any figure would be a guess.
 */
evVsFair: number | null; 
/**
 * Fair probability at the close once the vig is removed, 0–1.
 */
fairProb: number | null }
/**
 * One point on a convergence curve.
 */
export type ConvergencePoint = { 
/**
 * Sample size at this point.
 */
sampleSize: number; 
/**
 * Regressed estimate at that sample size.
 */
regressed: number }
/**
 * How a correlated parlay prices against its independent counterpart.
 */
export type Correlated = { 
/**
 * Product of the leg probabilities — what a parlay calculator assumes.
 */
independentProb: number; 
/**
 * Joint probability once the legs are coupled.
 */
correlatedProb: number; 
/**
 * Independent price, in decimal odds.
 */
independentDecimal: number; 
/**
 * Correlated price, in decimal odds.
 */
correlatedDecimal: number; 
/**
 * Relative change in probability, as a fraction.
 * 
 * Positive means the correlation helps: the parlay is likelier than the
 * product of its legs.
 */
relativeChange: number; 
/**
 * The correlation actually used, after any clamping.
 */
correlationUsed: number; 
/**
 * True when the requested correlation was outside the range an
 * equicorrelated matrix can represent for this many legs.
 */
correlationWasClamped: boolean; 
/**
 * `None` when solved exactly; `Some(seed)` when simulated.
 * 
 * Crosses the wire as a decimal string — see [`crate::seed_repr`].
 */
simulationSeed: string | null }
/**
 * Which assumption to make about where the margin sits.
 */
export type DevigMethod = 
/**
 * Equal margin — subtract the overround evenly across outcomes.
 */
"EM" | 
/**
 * Margin proportional to odds — divide through by the book total.
 */
"MPTO" | 
/**
 * Shin (1993) — insider-trading model, marks longshots up more.
 */
"SHIN" | 
/**
 * Odds ratio — find the exponent `c` where `Σ pᶜ = 1`.
 */
"OR" | 
/**
 * Logarithmic — shift every outcome by a constant in log-odds space.
 */
"LOG"
/**
 * One devig method's verdict on a market.
 */
export type DevigRow = { 
/**
 * Which method produced this.
 */
method: DevigMethod; 
/**
 * Human-readable name for display.
 */
name: string; 
/**
 * Fair probabilities, when the method converged.
 */
fairProbs: number[] | null; 
/**
 * Why the method could not produce them, when it could not.
 * 
 * Kept beside the row so the UI can explain an empty column instead of
 * just showing a dash.
 */
error: MathError | null }
/**
 * A Dirichlet posterior over a market with any number of outcomes.
 */
export type DirichletPosterior = { 
/**
 * Prior concentration per outcome, from the market.
 */
priorAlphas: number[]; 
/**
 * Posterior concentration per outcome.
 */
posteriorAlphas: number[]; 
/**
 * Posterior probabilities, summing to 1.
 */
posteriorProbs: number[]; 
/**
 * Largest move off the market across outcomes, in probability points.
 */
maxShiftFromMarket: number }
/**
 * Which family to sample from.
 */
export type Distribution = 
/**
 * Counts with variance equal to the mean. Goals, aces.
 */
"poisson" | 
/**
 * Overdispersed counts — variance a multiple of the mean.
 */
"nbinom" | 
/**
 * Continuous, right-skewed, variance twice the mean.
 */
"gamma" | 
/**
 * Continuous, heavier right tail. Yardage, minutes.
 */
"lognormal"
/**
 * What a posterior is worth against a price on offer.
 */
export type Edge = { 
/**
 * Posterior probability minus the price's implied probability, in points.
 */
edgePoints: number; 
/**
 * Expected value as a fraction of stake.
 */
evFraction: number; 
/**
 * The American price the posterior implies.
 */
fairOdds: number; 
/**
 * Whether the edge clears the threshold and the EV is positive.
 */
isBet: boolean }
/**
 * Build and version information for the math engine.
 */
export type EngineInfo = { 
/**
 * Version of the `bettor-core` math crate.
 */
coreVersion: string; 
/**
 * Version of this desktop shell.
 */
shellVersion: string; 
/**
 * Whether the engine was compiled with optimizations. Monte Carlo results
 * from an unoptimized build are correct but far slower.
 */
optimized: boolean }
/**
 * What a bet is worth at a given price and true probability.
 */
export type ExpectedValue = { 
/**
 * EV as a fraction of stake. `0.05` is a 5% edge.
 */
evFraction: number; 
/**
 * EV in currency, for the stake supplied.
 */
evAmount: number; 
/**
 * Probability implied by the price taken, 0–1.
 */
impliedProb: number; 
/**
 * Win rate needed to break even at this price, 0–1. Identical to
 * [`Self::implied_prob`], named for what it means to a bettor.
 */
breakeven: number; 
/**
 * True probability minus implied probability, in probability points.
 */
edgePoints: number }
/**
 * A hedge on an open position.
 */
export type Hedge = { 
/**
 * Stake to place on the opposing side.
 */
hedgeStake: number; 
/**
 * Original stake plus hedge stake.
 */
totalRisk: number; 
/**
 * Net profit if the original bet wins.
 */
profitIfOriginalWins: number; 
/**
 * Net profit if the hedge wins.
 */
profitIfHedgeWins: number; 
/**
 * The worse of the two outcomes — what you are actually locking in.
 */
worstCase: number; 
/**
 * [`Self::worst_case`] as a fraction of total risk.
 */
roi: number }
/**
 * What to do about an open position when the price has moved.
 */
export type HedgeGoal = 
/**
 * Equalise the return so the outcome no longer matters.
 */
"guarantee" | 
/**
 * Stake only enough to recover the original stake if the hedge lands.
 */
"recoverStake"
/**
 * One bar of a histogram.
 */
export type HistogramBin = { 
/**
 * Left edge, inclusive.
 */
rangeStart: number; 
/**
 * Right edge, exclusive (except in the final bin).
 */
rangeEnd: number; 
/**
 * How many samples landed here.
 */
count: number; 
/**
 * [`Self::count`] as a fraction of all samples.
 */
freq: number }
/**
 * What a book is charging on a two-sided market.
 */
export type Hold = { 
/**
 * Implied probability of side A, as priced.
 */
impliedA: number; 
/**
 * Implied probability of side B, as priced.
 */
impliedB: number; 
/**
 * The two implied probabilities added together. Above 1.0 for a real book.
 */
totalImplied: number; 
/**
 * The overround as a fraction of the book: `total − 1`.
 * 
 * Negative means the two sides can be backed together for a guaranteed
 * profit. See [`Hold::is_arbitrage`].
 */
hold: number; 
/**
 * Fair probability of side A once the margin is removed proportionally.
 */
noVigProbA: number; 
/**
 * Fair probability of side B once the margin is removed proportionally.
 */
noVigProbB: number }
/**
 * The projected score line behind a spread and total.
 */
export type ImpliedScores = { 
/**
 * Points projected for the home team.
 */
home: number; 
/**
 * Points projected for the away team.
 */
away: number }
/**
 * Optimal stake under the Kelly criterion.
 */
export type Kelly = { 
/**
 * Full-Kelly fraction of bankroll. Negative means do not bet.
 */
fullFraction: number; 
/**
 * Fraction after applying the chosen Kelly multiplier.
 */
adjustedFraction: number; 
/**
 * Stake implied by [`Self::full_fraction`], floored at zero.
 */
fullStake: number; 
/**
 * Stake implied by [`Self::adjusted_fraction`], floored at zero.
 */
adjustedStake: number; 
/**
 * EV of the bet as a fraction of stake.
 */
evFraction: number; 
/**
 * True probability minus implied, in probability points.
 */
edgePoints: number }
/**
 * A priced ladder of alternate lines.
 */
export type Ladder = { 
/**
 * The true line backed out of the main market.
 */
trueLine: number; 
/**
 * One row per alternate, cheapest to longest.
 */
rows: LadderRow[]; 
/**
 * Rows omitted because the probability was beyond `[0.005, 0.995]`.
 * 
 * The TS dropped these silently.
 */
omitted: number }
/**
 * One rung of an alternate-line ladder.
 */
export type LadderRow = { 
/**
 * The alternate line.
 */
line: number; 
/**
 * Fair probability of covering it, 0–1.
 */
fairProb: number; 
/**
 * The American price that probability implies.
 */
fairOdds: number }
/**
 * Which of two competing lines is better, and by how much.
 */
export type LineComparison = { 
/**
 * True line implied by the first quote.
 */
trueLineA: number; 
/**
 * True line implied by the second quote.
 */
trueLineB: number; 
/**
 * Which is better: `None` for a tie.
 */
better: Side | null; 
/**
 * Distance between the two implied true lines, in points.
 */
diff: number }
/**
 * Scoring variance for one sport, and the markets it posts.
 */
export type LineSport = { 
/**
 * Stable identifier, e.g. `"nba"`.
 */
key: string; 
/**
 * Display name, e.g. `"NBA"`.
 */
label: string; 
/**
 * Standard deviation of the margin of victory, in points.
 */
spreadStd: number; 
/**
 * Standard deviation of the game total, in points.
 */
totalStd: number; 
/**
 * Which markets this sport is usually priced on.
 */
markets: Market[]; 
/**
 * True where a draw is a distinct moneyline outcome.
 */
threeWayMoneyline: boolean }
/**
 * A precision-weighted combination of two margin estimates.
 */
export type MarginPosterior = { 
/**
 * Posterior expected margin.
 */
margin: number; 
/**
 * The same figure as a spread, which is its negation.
 */
spread: number; 
/**
 * Posterior standard deviation. Always below both inputs — combining two
 * estimates cannot make you less certain.
 */
stdDev: number; 
/**
 * Share of the posterior mean contributed by the market, 0–1.
 */
marketWeight: number }
/**
 * Which market the two positions sit on.
 */
export type Market = 
/**
 * A point spread. Lines are folded onto the favorite's margin axis, so
 * `-3.5` and `+3.5` describe the same number.
 */
"spread" | 
/**
 * A total. Lines are used as posted.
 */
"total"
/**
 * Every market derivable from a score matrix.
 */
export type MarketProbs = { 
/**
 * Probability the home side wins outright.
 */
homeWin: number; 
/**
 * Probability of a draw. Zero when draws were redistributed.
 */
draw: number; 
/**
 * Probability the away side wins outright.
 */
awayWin: number; 
/**
 * The ten most likely exact scorelines, most likely first.
 */
topScorelines: Scoreline[]; 
/**
 * Cover probabilities at each requested spread.
 */
spreads: SpreadProb[]; 
/**
 * Over/under probabilities at each requested total.
 */
totals: TotalProb[] }
/**
 * Markets derived from a scoreline model, plus the grid's truncation mass.
 */
export type MatchMarkets = { 
/**
 * Moneyline, spreads, totals, and top scorelines.
 */
markets: MarketProbs; 
/**
 * Probability that fell outside the grid before renormalising.
 * 
 * A large value means `max_score` is too low for these scoring rates.
 */
truncationMass: number }
/**
 * How a match model was parameterised.
 */
export type MatchModel = 
/**
 * Independent Poisson scoring.
 */
{ kind: "poisson"; lambda_home: number; lambda_away: number } | 
/**
 * Overdispersed scoring, for blowout-prone matchups.
 */
{ kind: "negativeBinomial"; mean_home: number; mean_away: number; r_home: number; r_away: number }
/**
 * Scoring rates and line menus for the match models.
 */
export type MatchSport = { 
/**
 * Stable identifier, e.g. `"soccer"`.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * What a unit of scoring is called — "Goals", "Runs".
 */
scoreLabel: string; 
/**
 * Typical home scoring rate.
 */
defaultHome: number; 
/**
 * Typical away scoring rate.
 */
defaultAway: number; 
/**
 * Negative binomial dispersion. Smaller means more overdispersed.
 */
defaultR: number; 
/**
 * Guidance on choosing `r`, shown beside the input.
 */
rHint: string; 
/**
 * Largest score the matrix is evaluated to.
 * 
 * Truncating drops real probability mass — see
 * [`crate::match_model::MatchMarkets::truncation_mass`], which reports
 * how much, so this can be checked rather than assumed.
 */
maxScore: number; 
/**
 * Spread lines worth pricing.
 */
spreadLines: number[]; 
/**
 * Total lines worth pricing.
 */
totalLines: number[]; 
/**
 * True where a draw is a possible result.
 */
allowDraw: boolean }
/**
 * Errors produced by invalid input to a math routine.
 * 
 * The TypeScript returns `null` on bad input, which collapses "you typed a
 * letter", "that probability is out of range", and "this solver did not
 * converge" into one indistinguishable value. Each gets its own variant here
 * so the UI can say something useful.
 */
export type MathError = 
/**
 * A string input could not be parsed in the expected odds format.
 */
{ kind: "parseOdds"; detail: { 
/**
 * The offending input, echoed back so the UI can highlight it.
 */
value: string; 
/**
 * The format that was expected: `"american"`, `"decimal"`, `"fractional"`.
 */
format: string } } | 
/**
 * A probability fell outside the range a routine accepts.
 */
{ kind: "probabilityOutOfRange"; detail: { 
/**
 * The probability that was rejected.
 */
value: number; 
/**
 * Why it was rejected, e.g. `"must be strictly between 0 and 1"`.
 */
reason: string } } | 
/**
 * A numeric argument was outside the domain the routine accepts.
 */
{ kind: "domainError"; detail: { 
/**
 * Name of the parameter, matching the public API's argument name.
 */
param: string; 
/**
 * The constraint that was violated, e.g. `"greater than zero"`.
 */
constraint: string; 
/**
 * The value supplied.
 */
value: number } } | 
/**
 * A collection argument had the wrong shape (too few legs, mismatched lengths).
 */
{ kind: "shapeError"; detail: { 
/**
 * What was being counted, e.g. `"parlay legs"`.
 */
what: string; 
/**
 * The requirement, e.g. `"at least 2"`.
 */
expected: string; 
/**
 * The count actually supplied.
 */
got: number } } | 
/**
 * An iterative solver ran out of iterations without meeting its tolerance.
 * 
 * Reported rather than swallowed: a devig method that silently returns its
 * last un-converged iterate is worse than one that admits it failed.
 */
{ kind: "noConvergence"; detail: { 
/**
 * Which solver gave up, e.g. `"shin"`.
 */
solver: string; 
/**
 * The iteration cap it hit.
 */
iterations: number; 
/**
 * How far from tolerance it still was when it stopped.
 */
residual: number } }
/**
 * A middle or trap, priced.
 */
export type Middle = { 
/**
 * True when the gap wins both tickets, false when it loses both.
 */
isMiddle: boolean; 
/**
 * Width of the gap between the two numbers.
 */
gapSize: number; 
/**
 * Probability the result lands inside the gap, 0–1.
 */
gapProb: number; 
/**
 * Market's expected value on the shared axis — the favorite's expected
 * margin, or the expected total.
 */
trueCenter: number; 
/**
 * Expected profit in currency.
 */
ev: number; 
/**
 * [`Self::ev`] as a fraction of everything staked.
 */
evFraction: number; 
/**
 * Total staked across both tickets.
 */
totalStaked: number; 
/**
 * Every way this resolves. Probabilities sum to 1.
 */
outcomes: Outcome[] }
/**
 * One side of the position.
 * 
 * Named for the direction that wins it rather than the team it is on, which
 * is what stops the two legs drifting into different sign conventions.
 */
export type MiddleLeg = { 
/**
 * The number bet, as posted.
 */
line: number; 
/**
 * Fair (devigged) probability this leg covers — see
 * [`crate::line::fair_cover_prob`].
 */
fairCoverProb: number; 
/**
 * Amount staked.
 */
stake: number; 
/**
 * Decimal price taken.
 */
decimalOdds: number }
/**
 * The three ways a price gets written.
 */
export type OddsFormat = 
/**
 * `-110`, `+250`.
 */
"american" | 
/**
 * `1.909`, `3.5`.
 */
"decimal" | 
/**
 * `10/11`, `5/2`.
 */
"fractional"
/**
 * A decimal price expressed every other way.
 */
export type OddsView = { 
/**
 * American price, e.g. `-110`.
 */
american: number; 
/**
 * Fractional numerator, e.g. `10` in `10/11`.
 */
fractionalNum: number; 
/**
 * Fractional denominator, e.g. `11` in `10/11`.
 */
fractionalDen: number; 
/**
 * Implied probability on a **0–1** scale (the TS used 0–100 here).
 */
probability: number }
/**
 * One way the position can resolve.
 */
export type Outcome = { 
/**
 * What happened, for display.
 */
label: string; 
/**
 * Probability of it, 0–1.
 */
probability: number; 
/**
 * Net profit across both tickets if it happens.
 */
netProfit: number }
/**
 * A priced parlay.
 */
export type Parlay = { 
/**
 * Combined decimal price — the product of every leg.
 */
decimal: number; 
/**
 * Combined probability implied, 0–1, assuming independence.
 */
impliedProb: number; 
/**
 * Return if every leg lands, stake included.
 */
payout: number; 
/**
 * Return minus stake.
 */
profit: number; 
/**
 * How many legs were priced.
 */
legCount: number }
/**
 * One position within a sport.
 */
export type PropPosition = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Stats commonly posted for this position.
 */
stats: PropStat[] }
/**
 * A prop simulation: samples, summarised.
 */
export type PropSimulation = { 
/**
 * Seed that produced this run. Pass it back to reproduce exactly.
 * 
 * A decimal string, not a number — see `resolve_seed`.
 */
seed: string; 
/**
 * Binned samples, ready to chart.
 */
histogram: HistogramBin[]; 
/**
 * Mean and standard deviation of the sample.
 */
stats: Stats; 
/**
 * Probability the prop goes over the line, 0–1.
 */
overProb: number; 
/**
 * Probability it does not, 0–1.
 * 
 * Reported rather than left as `1 - over_prob` for the caller to work
 * out. The frontend does not compute, and a complement derived on the
 * far side of the IPC boundary would silently stop agreeing with this
 * side the moment pushes at the line are handled differently.
 */
underProb: number; 
/**
 * Fair American price for the over.
 */
overFairOdds: number; 
/**
 * Fair American price for the under.
 */
underFairOdds: number }
/**
 * Prop presets for one sport.
 */
export type PropSport = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Positions this sport prices props for.
 */
positions: PropPosition[] }
/**
 * One prop market, and the distribution that fits its shape.
 */
export type PropStat = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * The distribution this stat is simulated from.
 */
distribution: Distribution; 
/**
 * A typical projection.
 */
defaultProjection: number; 
/**
 * A typical posted line.
 */
defaultLine: number; 
/**
 * What the numbers are measured in.
 */
unit: string }
/**
 * A regressed estimate with its uncertainty.
 */
export type Regressed = { 
/**
 * Shrinkage-adjusted estimate of true talent.
 */
estimate: number; 
/**
 * Weight the observed sample earned, 0–1.
 */
weight: number; 
/**
 * Lower bound of the 90% interval.
 */
lower: number; 
/**
 * Upper bound of the 90% interval.
 */
upper: number }
/**
 * Regression presets for one sport.
 */
export type RegressionSport = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Stats with published regression constants.
 */
stats: RegressionStat[] }
/**
 * One regressable stat.
 */
export type RegressionStat = { 
/**
 * Stable identifier.
 */
key: string; 
/**
 * Display name.
 */
label: string; 
/**
 * Sample size at which observed and league average carry equal weight.
 */
regressionConstant: number; 
/**
 * The population mean this stat regresses toward.
 */
leagueAverage: number; 
/**
 * An illustrative hot-start observation.
 */
defaultObserved: number; 
/**
 * An illustrative sample size.
 */
defaultSampleSize: number; 
/**
 * What the stat is measured in.
 */
unit: string; 
/**
 * What the sample is counted in — plate appearances, shots, attempts.
 */
sampleUnit: string }
/**
 * Parameters for a survival simulation.
 */
export type RuinInput = { 
/**
 * True win probability, 0–1.
 */
winProb: number; 
/**
 * Decimal price of each bet.
 */
decimalOdds: number; 
/**
 * Flat stake per bet.
 */
betSize: number; 
/**
 * Starting bankroll.
 */
bankroll: number; 
/**
 * How many bets to simulate.
 */
numBets: number; 
/**
 * How many independent paths to run.
 */
numSims: number }
/**
 * Outcome of a survival simulation.
 */
export type RuinResult = { 
/**
 * Seed that produced this run. Feed it back to reproduce exactly.
 * 
 * Crosses the wire as a decimal string — see [`crate::seed_repr`].
 */
seed: string; 
/**
 * Fraction of paths that went broke, 0–1.
 */
ruinProb: number; 
/**
 * EV of a single bet, in currency.
 */
evPerBet: number; 
/**
 * EV as a fraction of stake.
 */
edge: number; 
/**
 * Median ending bankroll across **all** paths, ruined counted as zero.
 */
medianEndingAll: number; 
/**
 * Mean ending bankroll across **all** paths, ruined counted as zero.
 */
meanEndingAll: number; 
/**
 * Median ending bankroll across **surviving** paths only.
 * 
 * This is the figure the TS labelled simply "median bankroll", beside a
 * mean computed over a different population.
 */
medianEndingSurvivors: number; 
/**
 * Mean of each path's worst peak-to-trough drop, as a fraction of peak.
 */
meanMaxDrawdown: number; 
/**
 * Median of the same, which is the more honest summary of a skewed figure.
 */
medianMaxDrawdown: number; 
/**
 * Longest run of consecutive losses seen in any path.
 * 
 * Not in the TS, and the statistic bettors most underestimate at long
 * prices: a real 21% shot loses more than twenty in a row routinely.
 */
longestLosingStreak: number; 
/**
 * Solvency over time, for charting.
 */
survivalCurve: SurvivalPoint[] }
/**
 * One exact scoreline and its probability.
 */
export type Scoreline = { 
/**
 * Home team's score.
 */
home: number; 
/**
 * Away team's score.
 */
away: number; 
/**
 * Probability of exactly this result.
 */
prob: number }
/**
 * Identifies one of two compared quotes.
 */
export type Side = 
/**
 * The first quote.
 */
"a" | 
/**
 * The second quote.
 */
"b"
/**
 * Everything the frontend needs to populate its sport pickers.
 */
export type SportConfig = { 
/**
 * Scoring spreads for line inversion and alternate-line ladders.
 */
lines: LineSport[]; 
/**
 * Scoring rates for the match models.
 */
matches: MatchSport[]; 
/**
 * Player prop presets, by sport and position.
 */
props: PropSport[]; 
/**
 * Regression constants and league averages, by sport and stat.
 */
regression: RegressionSport[] }
/**
 * Cover probabilities for one spread.
 */
export type SpreadProb = { 
/**
 * The line, from the home side's perspective.
 */
spread: number; 
/**
 * Probability the home side covers.
 */
homeCovers: number; 
/**
 * Probability the away side covers.
 */
awayCovers: number; 
/**
 * Probability of a push. Nonzero only on whole-number lines.
 * 
 * The TS dropped this mass entirely, so the two sides did not sum to 1.
 */
push: number }
/**
 * Mean and standard deviation of a sample.
 */
export type Stats = { 
/**
 * Sample mean.
 */
mean: number; 
/**
 * Sample standard deviation, using the `n − 1` denominator.
 */
stdDev: number }
/**
 * Fraction of paths still solvent at a given bet number.
 */
export type SurvivalPoint = { 
/**
 * Bet index.
 */
bet: number; 
/**
 * Fraction of paths still able to place a bet, 0–1.
 */
survival: number }
/**
 * A complete teaser, priced.
 */
export type Teaser = { 
/**
 * Per-leg analysis, in the order supplied.
 */
legs: TeaserLegAnalysis[]; 
/**
 * Probability every leg covers, assuming independence.
 */
combinedProb: number; 
/**
 * American price that probability implies.
 */
fairOdds: number; 
/**
 * Win rate needed to break even at the price offered, 0–1.
 */
breakeven: number; 
/**
 * Expected value as a fraction of stake.
 */
evFraction: number; 
/**
 * True when any leg crosses a key number, meaning the normal model is
 * understating this teaser's true value.
 */
modelIgnoresKeyNumbers: boolean }
/**
 * One leg of a teaser, as posted.
 */
export type TeaserLeg = { 
/**
 * The spread before teasing, in the bettor's favour when positive.
 */
spread: number; 
/**
 * Fair (devigged) probability of covering that spread — see
 * [`crate::line::fair_cover_prob`].
 */
fairCoverProb: number }
/**
 * One leg, priced after the points are applied.
 */
export type TeaserLegAnalysis = { 
/**
 * The spread as posted.
 */
spread: number; 
/**
 * The spread after the teaser points are added.
 */
teasedSpread: number; 
/**
 * True line backed out of the posted spread and its fair price.
 */
trueLine: number; 
/**
 * Probability of covering the teased spread, 0–1.
 */
coverProb: number; 
/**
 * The American price that probability implies.
 */
fairOdds: number; 
/**
 * Key numbers the tease moves through.
 * 
 * Reported for judgement, **not** priced in — see the module docs.
 */
keyNumbersCrossed: number[] }
/**
 * Over/under probabilities for one total.
 */
export type TotalProb = { 
/**
 * The line.
 */
line: number; 
/**
 * Probability the total goes over.
 */
over: number; 
/**
 * Probability the total stays under.
 */
under: number; 
/**
 * Probability of a push.
 */
push: number }
/**
 * Which side of a total.
 */
export type TotalSide = 
/**
 * Betting the game goes over.
 */
"over" | 
/**
 * Betting the game stays under.
 */
"under"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
